const tableData = [
  //5.1师资情况
  {
    firstLevel:'5.1师资情况',
    secondLevel:'教室资质',
    weight:'',
    remark:'带教负责人具有高年资住院以上资格10分',
  },
  //5.2进修生规模
  {
    firstLevel:'5.2进修生规模',
    secondLevel:'接收进修人数',
    weight:'',
    remark:'接受三甲医院',
  },
  //5.3教学工作量
  {
    firstLevel:'5.3教学工作量',
    secondLevel:'工作量完成情况',
    weight:'',
    remark:'完成病种及例数达到90%的学生的百分比，比例递增给分',
  },
  {
    firstLevel:'',
    secondLevel:'教学查房',
    weight:'',
    remark:'实习期间教学查房每月大于1次，要完整查房记录',
  },
  {
    firstLevel:'',
    secondLevel:'小讲座',
    weight:'',
    remark:'每个月不少于2次',
  },
  {
    firstLevel:'',
    secondLevel:'病例讨论',
    weight:'',
    remark:'每个月不少于2次',
  },
  {
    firstLevel:'',
    secondLevel:'技能培训',
    weight:'',
    remark:'每个月不少于4次',
  },
  {
    firstLevel:'',
    secondLevel:'选修课',
    weight:'',
    remark:'每个月不少于？',
  },
  //5.4教学质量评估
  {
    firstLevel:'5.4教学质量评估',
    secondLevel:'教学效果评估结果',
    weight:'',
    remark:'评估优比例大于等于90%，每降5个百分点扣5分',
  },
  //5.5日常管理
  {
    firstLevel:'5.5日常管理',
    secondLevel:'考勤审核情况',
    weight:'',
    remark:'考勤记录全部审核',
  },
  {
    firstLevel:'',
    secondLevel:'审批（符合响应时间）',
    weight:'',
    remark:'',
  },
  {
    firstLevel:'',
    secondLevel:'组织评优',
    weight:'',
    remark:'',
  },
]
export  default tableData
