 const tableData = [
   //6.1教学改革活动
   {
     firstLevel:'6.1教学改革活动',
     secondLevel:'教改活动',
     weight:'',
     remark:'采用PBL/翻转课堂及其他新教学方法1项得5分',
    },
   //6.2教学建设
   {
     firstLevel:'6.2教学建设',
     secondLevel:'教材建设',
     weight:'',
     remark:'主编1，副主编0.5，编委0.2；国家级、省部级及校级教材等级系数分别为3、2、1',
    },
   {
     firstLevel:'',
     secondLevel:'课程建设',
     weight:'',
     remark:'主要完成人1，第二完成人0.5，其他完成人0.3；校级、院级系数分别为2,1',
    },
   //6.3教学研究
   {
     firstLevel:'6.3教学研究',
     secondLevel:'教学课题',
     weight:'',
     remark:'主要完成人1，第二完成人0.5；省部级、校级、院级系数分别为2、1、0.5',
    },
   {
     firstLevel:'',
     secondLevel:'教学论文',
     weight:'',
     remark:'中文核心或统计源、一般期刊2、1',
    },
   {
     firstLevel:'',
     secondLevel:'教学成果',
     weight:'',
     remark:'主要完成人1，第二完成人0.5，其他完成人0.3；国家级、省部级、校级系数分别为3、2、1',
    },
   //6.4教育奖励
   {
     firstLevel:'6.4教育奖励',
     secondLevel:'教学竞赛',
     weight:'',
     remark:'校级特等、一等、二等、三等分别3、2、1、0.5',
    },
   {
     firstLevel:'',
     secondLevel:'指导学生参与竞赛',
     weight:'',
     remark:'国家级、省级、校级3、2、1',
    },
   //6.5师资培养
   {
     firstLevel:'6.5师资培养',
     secondLevel:'新增',
     weight:'',
     remark:'开展师资培训工作，新增博导，硕导，教授，副教授，讲师，获得培训资格证书，',
    },
   //6.7教学态度
   {
     firstLevel:'6.7教学态度',
     secondLevel:'核心领导小组会议',
     weight:'',
     remark:'要求每半年至少1次，教学内容记录详细，未达标准者该项分值为0',
    },
   //6.8教学档案
   {
     firstLevel:'6.8教学档案',
     secondLevel:'查阅教学档案',
     weight:'',
     remark:'教学相关文件资料保存齐全',
    },
]
export  default tableData
