const tableData = [

  //2.1师资情况
  {
    firstLevel:'2.1师资情况',
    secondLevel:'实习带教',
    weight:'',
    remark:'实习带教负责人具有高年资住院以上资格得10分',
  },
  //2.2教学工作量
  {
    firstLevel:'2.2教学工作量',
    secondLevel:'教学查房',
    weight:'',
    remark:'实习期间教学查房每月大于1次，要完整查房记录',
  },
  {
    firstLevel:'',
    secondLevel:'小讲座',
    weight:'',
    remark:'每个月不少于2次',
  },
  {
    firstLevel:'',
    secondLevel:'病例讨论',
    weight:'',
    remark:'每个月不少于2次',
  },
  {
    firstLevel:'',
    secondLevel:'技能培训',
    weight:'',
    remark:'每个月不少于4次',
  },
  {
    firstLevel:'',
    secondLevel:'选修课',
    weight:'',
    remark:'每个月不少于？',
  },
  //2.3教学质量评估
  {
    firstLevel:'2.3教学质量评估',
    secondLevel:'教学效果评估结果',
    weight:'',
    remark:'评估优比例大于等于90%，每降5个百分点扣5分',
  },
  //2.4日常管理
  {
    firstLevel:'2.4日常管理',
    secondLevel:'考勤审核情况',
    weight:'',
    remark:'考勤记录全部审核',
  },
  {
    firstLevel:'',
    secondLevel:'审批（符合响应时间）',
    weight:'',
    remark:'',
  },
  {
    firstLevel:'',
    secondLevel:'组织评优',
    weight:'',
    remark:'',
  },
]
export  default tableData
