const tableData = [
  //4.1教学资质
  {
    firstLevel:'4.1教学资质',
    secondLevel:'基地级别',
    weight:'',
    remark:'国内认证的住院医师培训基地10分，专科医师培训基地10分',
  },
  {
    firstLevel:'',
    secondLevel:'教室资质',
    weight:'',
    remark:'带教负责人具有高年资住院以上资格10分',
  },
  //4.2培训规模
  {
    firstLevel:'4.2培训规模',
    secondLevel:'接收外院培训人数',
    weight:'',
    remark:'每年大于等于人（大内科大于等于10人，大外科大于等于6人，医学影像科大于等于6人），未达标准者该项分值为0',
  },
  //4.3培训质量
  {
    firstLevel:'4.3培训质量',
    secondLevel:'工作量完成情况',
    weight:'',
    remark:'完成病种及例数达到90%的学生的百分比，比例递增给分',
  },
  {
    firstLevel:'',
    secondLevel:'出科考核情况',
    weight:'',
    remark:'出科考核通过人数所占百分比',
  },
  {
    firstLevel:'',
    secondLevel:'年度考核情况',
    weight:'',
    remark:'协助教育处完成年度考核，未达标准者该项分值为0',
  },
  {
    firstLevel:'',
    secondLevel:'二阶段通过率',
    weight:'',
    remark:'',
  },
  //4.4教学工作量
  {
    firstLevel:'4.4教学工作量',
    secondLevel:'教学查房',
    weight:'',
    remark:'教学查房每月大于1次，要完整查房记录',
  },
  {
    firstLevel:'',
    secondLevel:'小讲座',
    weight:'',
    remark:'每个月不少于2次',
  },
  {
    firstLevel:'',
    secondLevel:'病例讨论',
    weight:'',
    remark:'每个月不少于2次',
  },
  {
    firstLevel:'',
    secondLevel:'技能培训',
    weight:'',
    remark:'每个月不少于4次',
  },
  {
    firstLevel:'',
    secondLevel:'选修课',
    weight:'',
    remark:'每个月不少于？',
  },
  //4.5教学质量评估
  {
    firstLevel:'4.5教学质量评估',
    secondLevel:'教学效果评估结果',
    weight:'',
    remark:'评估优比例大于等于90%，每降5个百分点扣5分',
  },
  //4.6日常管理
  {
    firstLevel:'4.6日常管理',
    secondLevel:'考勤审核情况',
    weight:'',
    remark:'考勤记录全部审核',
  },
  {
    firstLevel:'',
    secondLevel:'审批（符合响应时间）',
    weight:'',
    remark:'',
  },
  {
    firstLevel:'',
    secondLevel:'组织评优',
    weight:'',
    remark:'',
  },
]
export  default tableData
