 const tableData = [
   //3.1导师资格
   {
     firstLevel:'3.1导师资格',
     secondLevel:'硕导',
     weight:'',
     remark:'占副高级职称人数的50%，每提高10%增加？？',
    },
   {
     firstLevel:'',
     secondLevel:'博导',
     weight:'',
     remark:'大于等于1个，没多一个加？分',
    },
   //3.2培养规模
   {
     firstLevel:'3.2培养规模',
     secondLevel:'硕士研究生毕业人数',
     weight:'',
     remark:'按期毕业90%以上给？？，80%以上给？？。。',
    },
   {
     firstLevel:'',
     secondLevel:'博士研究生毕业人数',
     weight:'',
     remark:'按期毕业70%以上给？？，60%以上给？？。。',
    },
   //3.3培养质量
   {
     firstLevel:'3.3培养质量',
     secondLevel:'硕士生发表论文情况',
     weight:'',
     remark:'硕士生人均发表论文数',
    },
   {
     firstLevel:'',
     secondLevel:'博士生发表论文情况',
     weight:'',
     remark:'博士生人均发表论文数',
    },
   {
     firstLevel:'',
     secondLevel:'学生获奖情况',
     weight:'',
     remark:'根据获奖情况，每多一个加？？分',
    },
   //3.4日常工作
   {
     firstLevel:'3.4日常工作',
     secondLevel:'按要求组织面试、开题、预答辩、答辩',
     weight:'',
     remark:'按照要求开展工作得分',
    },
   //3.5教学质量评估
   {
     firstLevel:'3.5教学质量评估',
     secondLevel:'教学效果评估结果',
     weight:'',
     remark:'评估优比例大于等于90%，每降5个百分点扣5分',
    },
]
export  default tableData
