 const tableData = [
   //导师资格
   {
     firstLevel:'导师资格',
     secondLevel:'博导',
     weight:'',
     remark:'',
    },
   {
     firstLevel:'',
     secondLevel:'硕导',
     weight:'',
     remark:'',
    },
   //培养质量
   {
     firstLevel:'培养质量',
     secondLevel:'全国优博/硕',
     weight:'',
     remark:'',
    },
   {
     firstLevel:'',
     secondLevel:'省级优博/硕',
     weight:'',
     remark:'',
    },
   {
     firstLevel:'',
     secondLevel:'校级优博/硕',
     weight:'',
     remark:'',
    },
   {
     firstLevel:'',
     secondLevel:'SCI',
     weight:'',
     remark:'',
    },
   {
     firstLevel:'',
     secondLevel:'中华系列',
     weight:'',
     remark:'',
    },
   {
     firstLevel:'',
     secondLevel:'统计源或核心',
     weight:'',
     remark:'',
    },
   {
     firstLevel:'',
     secondLevel:'论著除外',
     weight:'',
     remark:'',
    },
   {
     firstLevel:'',
     secondLevel:'临床能力考核通过',
     weight:'',
     remark:'四证合一',
    },
   {
     firstLevel:'',
     secondLevel:'研究生获国家级荣誉',
     weight:'',
     remark:'',
    },
   {
     firstLevel:'',
     secondLevel:'研究生获省级荣誉',
     weight:'',
     remark:'',
    },
   {
     firstLevel:'',
     secondLevel:'研究生获校级荣誉',
     weight:'',
     remark:'',
    },
   {
     firstLevel:'',
     secondLevel:'研究生获得课题情况',
     weight:'',
     remark:'',
    },
   //教学工作
   {
     firstLevel:'教学工作',
     secondLevel:'选修课',
     weight:'',
     remark:'',
    },
   {
     firstLevel:'',
     secondLevel:'研究生开题',
     weight:'',
     remark:'',
    },
   {
     firstLevel:'',
     secondLevel:'中期考核',
     weight:'',
     remark:'',
    },
   {
     firstLevel:'',
     secondLevel:'研究生答辩通过',
     weight:'',
     remark:'',
    },
   {
     firstLevel:'',
     secondLevel:'技能考核监考',
     weight:'',
     remark:'',
    },
   //评估
   {
     firstLevel:'评估',
     secondLevel:'教研室评价',
     weight:'',
     remark:'',
    },
   {
     firstLevel:'',
     secondLevel:'研究生评价',
     weight:'',
     remark:'',
    },
   {
     firstLevel:'',
     secondLevel:'教育处评价',
     weight:'',
     remark:'',
    },
   //日常管理
   {
     firstLevel:'日常管理',
     secondLevel:'考勤',
     weight:'',
     remark:'',
    },
   {
     firstLevel:'',
     secondLevel:'审批',
     weight:'',
     remark:'',
    },
   {
     firstLevel:'',
     secondLevel:'评优',
     weight:'',
     remark:'',
    },
   {
     firstLevel:'',
     secondLevel:'目标手册完成',
     weight:'',
     remark:'',
    },
]
export  default tableData
