 const tableData = [
   //教学建设
   {
     firstLevel:'教学建设',
     secondLevel:'教材建设',
     weight:'',
     remark:'主编1，副主编0.5，编委0.2；国家级、省部级及校级教材等级系数分别为3、2、1',
    },
   {
     firstLevel:'',
     secondLevel:'课程建设',
     weight:'',
     remark:'主要完成人1，第二完成人0.5，其他完成人0.3；校级、院级系数分别为2,1',
    },
   //教学研究
   {
     firstLevel:'教学研究',
     secondLevel:'教学课题',
     weight:'',
     remark:'主要完成人1，第二完成人0.5；省部级、校级、院级系数分别为2、1、0.5',
    },
   {
     firstLevel:'',
     secondLevel:'教学论文',
     weight:'',
     remark:'中文核心或统计源、一般期刊2、1',
    },
   {
     firstLevel:'',
     secondLevel:'教学成果',
     weight:'',
     remark:'主要完成人1，第二完成人0.5，其他完成人0.3；国家级、省部级、校级系数分别为3、2、1',
    },
   //教育奖励
   {
     firstLevel:'教育奖励',
     secondLevel:'教学竞赛',
     weight:'',
     remark:'校级特等、一等、二等、三等分别3、2、1、0.5',
    },
   {
     firstLevel:'',
     secondLevel:'指导学生参与竞赛',
     weight:'',
     remark:'国家级、省级、校级3、2、1',
    },
   //师资培养
   {
     firstLevel:'师资培养',
     secondLevel:'担任师资培养讲师',
     weight:'',
     remark:'',
    },
   //个人能力提升
   {
     firstLevel:'个人能力提升',
     secondLevel:'参加学术会议或培训',
     weight:'',
     remark:'',
    },
   {
     firstLevel:'',
     secondLevel:'获得师资培训资格证书',
     weight:'',
     remark:'',
    },
   {
     firstLevel:'',
     secondLevel:'出国研修三个月以上',
     weight:'',
     remark:'',
    },
   {
     firstLevel:'',
     secondLevel:'国内外出进修（三个月以上）',
     weight:'',
     remark:'',
    },
]
export  default tableData
