var data = {
  'sceneName': '测试05030944',
  'sceneType': 'FREE',
  'startTime': '2018-05-03 09:44:00',
  'endTime': '2018-05-03 17:44:00',
  'setupTime': '',
  'restNum': '',
  'restTime': '',
  'moveTime': '',
  'basicsTime': 60,
  'isSpMove': 'NO',
  'examineeNum': 7,
  'stationNum': 2,
  'scoringMethod': 'SCORE',
  'step': '',
  'isRest': '',
  'status': 'UNPUBLISH',
  'managerList': [],
  'userList': [{'userId': 12653, 'userName': '中心管理员', 'specialty': '管理'}, {'userId': 12654, 'userName': '唐漫漫', 'specialty': '护理'}, {
    'userId': 12655,
    'userName': '郭才宁',
    'specialty': '管理'
  }, {'userId': 12656, 'userName': '何艳芳', 'specialty': '管理'}, {'userId': 12657, 'userName': '聂华林', 'specialty': '管理'}, {
    'userId': 12658,
    'userName': '袁乐',
    'specialty': '管理'
  }, {'userId': 12668, 'userName': '唐晓鸿', 'specialty': ''}],
  'spList': [],
  'stationList': [{
    'stationName': '考站1',
    'stationType': 'ORDINARY',
    'timeCount': 600,
    'number': 1,
    'randomType': 'SYSTEM',
    'randomNum': 1,
    'isQueue': 'NO',
    'queueNum': '',
    'queueOrder': '',
    'isDraw': 'NO',
    'drawNum': '',
    'roomIds': '107',
    'stationWeight': 0.5,
    'roomSpecialtyList': [{'roomId': 107, 'specialty': ''}],
    'stationContentList': [{
      '_id': 0,
      'contentName': '考核内容1',
      'scoreTableIds': '68,67',
      'scoreTableList': [{'scoreTableId': 68, 'scoreTableName': '评分表2'}, {'scoreTableId': 67, 'scoreTableName': '评分表1'}],
      'spScoreTableId': '',
      'spScoreTableName': '',
      'caseId': 5,
      'caseName': '病例1',
      'scriptId': '',
      'scriptName': '',
      'timeCount': 60,
      'paperContentList': []
    }],
    'roomTeacherList': [{
      'teacherId': 12700,
      'teacherName': '闫芳带教老师1',
      'weight': 0.5,
      'userId': 12700,
      'userName': '闫芳带教老师1',
      'roomId': 107,
      'contentScoreTableList': [{'scoreTableId': 67, 'scoreTableName': '评分表1', 'contentName': '', 'oldScoreTableId': 67}]
    }, {
      'teacherId': 12701,
      'teacherName': '闫芳带教老师2',
      'weight': 0.5,
      'userId': 12701,
      'userName': '闫芳带教老师2',
      'roomId': 107,
      'contentScoreTableList': [{'scoreTableId': 68, 'scoreTableName': '评分表2', 'contentName': '', 'oldScoreTableId': 68}]
    }]
  }, {
    'stationName': '考站2',
    'stationType': 'ORDINARY',
    'timeCount': 600,
    'number': 1,
    'randomType': 'SYSTEM',
    'randomNum': 1,
    'isQueue': 'NO',
    'queueNum': '',
    'queueOrder': '',
    'isDraw': 'NO',
    'drawNum': '',
    'roomIds': '106',
    'stationWeight': 0.5,
    'roomSpecialtyList': [{'roomId': 106, 'specialty': ''}],
    'stationContentList': [{
      '_id': 0,
      'contentName': '内容1',
      'scoreTableIds': '68,67',
      'scoreTableList': [{'scoreTableId': 68, 'scoreTableName': '评分表2'}, {'scoreTableId': 67, 'scoreTableName': '评分表1'}],
      'spScoreTableId': '',
      'spScoreTableName': '',
      'caseId': 5,
      'caseName': '病例1',
      'scriptId': '',
      'scriptName': '',
      'timeCount': 60,
      'paperContentList': []
    }],
    'roomTeacherList': [{
      'teacherId': 12691,
      'teacherName': '张三',
      'weight': 0.5,
      'userId': 12691,
      'userName': '张三',
      'roomId': 106,
      'contentScoreTableList': [{'scoreTableId': 67, 'scoreTableName': '评分表1', 'contentName': '', 'oldScoreTableId': 67}]
    }, {
      'teacherId': 12693,
      'teacherName': '李四',
      'weight': 0.5,
      'userId': 12693,
      'userName': '李四',
      'roomId': 106,
      'contentScoreTableList': [{'scoreTableId': 68, 'scoreTableName': '评分表2', 'contentName': '', 'oldScoreTableId': 68}]
    }]
  }]
}

var b = {
  'sceneName': '测试05031439',
  'sceneType': 'FREE',
  'startTime': '2018-05-03 14:39:00',
  'endTime': '2018-05-04 14:39:00',
  'setupTime': '',
  'restNum': '',
  'restTime': '',
  'moveTime': '',
  'basicsTime': 60,
  'isSpMove': 'NO',
  'examineeNum': 7,
  'stationNum': 1,
  'scoringMethod': 'SCORE',
  'step': '10',
  'isRest': 'NO',
  'status': 'UNPUBLISH',
  'managerList': [],
  'userList': [{'userId': 12653, 'userName': '中心管理员', 'specialty': '管理'}, {'userId': 12654, 'userName': '唐漫漫', 'specialty': '护理'}, {
    'userId': 12655,
    'userName': '郭才宁',
    'specialty': '管理'
  }, {'userId': 12656, 'userName': '何艳芳', 'specialty': '管理'}, {'userId': 12657, 'userName': '聂华林', 'specialty': '管理'}, {
    'userId': 12658,
    'userName': '袁乐',
    'specialty': '管理'
  }, {'userId': 12668, 'userName': '唐晓鸿', 'specialty': ''}],
  'spList': [],
  'stationList': [{
    'stationName': '考站1',
    'stationType': 'THEORY',
    'timeCount': 600,
    'number': 1,
    'randomType': 'SYSTEM',
    'randomNum': 1,
    'isQueue': 'NO',
    'queueNum': '',
    'queueOrder': '',
    'isDraw': 'NO',
    'drawNum': '',
    'roomIds': '107',
    'stationWeight': 1,
    'roomSpecialtyList': [{'roomId': 107, 'specialty': ''}],
    'stationContentList': [{
      '_id': 0,
      'contentName': '试卷1',
      'scoreTableIds': '',
      'scoreTableList': [],
      'spScoreTableId': '',
      'spScoreTableName': '',
      'caseId': '',
      'caseName': '',
      'scriptId': '',
      'scriptName': '',
      'timeCount': 60,
      'paperContentList': [{
        'theId': 1,
        'types': 'RADIO',
        'subject': '<p>单选题题目</p>',
        'optionScore': '10',
        'options': 'B',
        'answerExplain': '<p>选2</p>',
        'optionsDtoList': [{'options': 'A', 'content': '<p>1</p>'}, {'options': 'B', 'content': '<p>2</p>'}, {'options': 'C', 'content': '<p>3</p>'}],
        'keyWords': null
      }]
    }],
    'roomTeacherList': []
  }]
}

var kz = {
  'sceneName': '测试空站',
  'sceneType': 'STANDARD',
  'startTime': '2018-05-07 15:32:00',
  'endTime': '',
  'setupTime': '',
  'restNum': '1',
  'restTime': 300,
  'moveTime': 120,
  'basicsTime': 300,
  'isSpMove': 'NO',
  'examineeNum': 7,
  'stationNum': 3,
  'scoringMethod': 'SCORE',
  'step': '1',
  'isRest': 'YES',
  'status': 'NOARRANGED',
  'managerList': [],
  'userList': [{'userId': 12653, 'userName': '中心管理员', 'specialty': '管理'}, {'userId': 12654, 'userName': '唐漫漫', 'specialty': '护理'}, {
    'userId': 12655,
    'userName': '郭才宁',
    'specialty': '管理'
  }, {'userId': 12656, 'userName': '何艳芳', 'specialty': '管理'}, {'userId': 12657, 'userName': '聂华林', 'specialty': '管理'}, {
    'userId': 12658,
    'userName': '袁乐',
    'specialty': '管理'
  }, {'userId': 12668, 'userName': '唐晓鸿', 'specialty': ''}],
  'spList': [],
  'stationList': [{
    'stationName': '正常站1',
    'stationType': 'ORDINARY',
    'timeCount': 1,
    'number': 1,
    'randomType': 'SYSTEM',
    'randomNum': 1,
    'isQueue': 'NO',
    'queueNum': '',
    'queueOrder': '',
    'isDraw': 'NO',
    'drawNum': '',
    'roomIds': '105',
    'stationWeight': 0.4,
    'roomSpecialtyList': [{'roomId': 105, 'specialty': ''}],
    'stationContentList': [{
      '_id': 0,
      'contentName': '内容1',
      'scoreTableIds': '61',
      'scoreTableList': [{'scoreTableId': 61, 'scoreTableName': 'colles骨折石膏固定操作评分表'}],
      'spScoreTableId': '',
      'spScoreTableName': '',
      'caseId': 1,
      'caseName': '501测试病例',
      'scriptId': '',
      'scriptName': '',
      'timeCount': 1,
      'paperContentList': [],
      'scoreTableId': 58,
      'scoreTableName': '抽搐与惊厥的问诊评分标准'
    }],
    'roomTeacherList': [{
      'teacherId': 12691,
      'teacherName': '张三',
      'weight': 1,
      'userId': 12691,
      'userName': '张三',
      'roomId': 105,
      'contentScoreTableList': [{'scoreTableId': 61, 'scoreTableName': 'colles骨折石膏固定操作评分表', 'contentName': '', 'oldScoreTableId': 61}]
    }]
  }, {
    'stationName': '空站',
    'stationType': 'REST',
    'timeCount': 1,
    'number': 1,
    'randomType': 'TEACHER',
    'randomNum': 1,
    'isQueue': 'NO',
    'queueNum': '',
    'queueOrder': '',
    'isDraw': 'NO',
    'drawNum': '',
    'roomIds': '104',
    'stationWeight': 0,
    'roomSpecialtyList': [{'roomId': 104, 'specialty': ''}],
    'stationContentList': [{
      '_id': 0,
      'contentName': '',
      'scoreTableIds': '',
      'scoreTableList': [],
      'spScoreTableId': '',
      'spScoreTableName': '',
      'caseId': '',
      'caseName': '',
      'scriptId': '',
      'scriptName': '',
      'timeCount': 1,
      'paperContentList': []
    }],
    'roomTeacherList': []
  }, {
    'stationName': '正常站2',
    'stationType': 'ORDINARY',
    'timeCount': 1,
    'number': 1,
    'randomType': 'SYSTEM',
    'randomNum': 1,
    'isQueue': 'NO',
    'queueNum': '',
    'queueOrder': '',
    'isDraw': 'NO',
    'drawNum': '',
    'roomIds': '103',
    'stationWeight': 0.6,
    'roomSpecialtyList': [{'roomId': 103, 'specialty': ''}],
    'stationContentList': [{
      '_id': 0,
      'contentName': '内容2',
      'scoreTableIds': '56',
      'scoreTableList': [{'scoreTableId': 56, 'scoreTableName': '少尿、无尿、多尿的评分标准'}],
      'spScoreTableId': '',
      'spScoreTableName': '',
      'caseId': 2,
      'caseName': '502病例',
      'scriptId': '',
      'scriptName': '',
      'timeCount': 1,
      'paperContentList': [],
      'scoreTableId': 57,
      'scoreTableName': '疼痛的问诊评分标准'
    }],
    'roomTeacherList': [{
      'teacherId': 12693,
      'teacherName': '李四',
      'weight': 1,
      'userId': 12693,
      'userName': '李四',
      'roomId': 103,
      'contentScoreTableList': [
        {'scoreTableId': 56, 'scoreTableName': '少尿、无尿、多尿的评分标准', 'contentName': '', 'oldScoreTableId': 56}
        ]
    }]
  }]
}
