 const tableData = [
   //培训手册完成情况
   {
     firstLevel:'培训手册完成情况',
     secondLevel:'病种完成情况',
     weight:'',
     remark:'完成率80%',
    },
   {
     firstLevel:'',
     secondLevel:'技能操作完成',
     weight:'',
     remark:'完成率80%',
    },
   //培训工作量
   {
     firstLevel:'培训工作量',
     secondLevel:'教学查房',
     weight:'',
     remark:'每个月1次，以上加分',
    },
   {
     firstLevel:'',
     secondLevel:'小讲座',
     weight:'',
     remark:'每个月2次，以上加分',
    },
   {
     firstLevel:'',
     secondLevel:'病例讨论',
     weight:'',
     remark:'每个月2次，以上加分',
    },
   {
     firstLevel:'',
     secondLevel:'技能培训',
     weight:'',
     remark:'每个月4次，以上加分',
    },

   //日常管理
   {
     firstLevel:'日常管理',
     secondLevel:'考勤情况',
     weight:'',
     remark:'全勤加分，旷工>扣分()',
    },
   {
     firstLevel:'',
     secondLevel:'手册书写完成',
     weight:'',
     remark:'按时提交(),出科一周()二周()',
    },
   {
     firstLevel:'',
     secondLevel:'教学评价完成度',
     weight:'',
     remark:'完成率80%',
    },
   {
     firstLevel:'',
     secondLevel:'奖励记录',
     weight:'',
     remark:'表扬信,优秀住院医师,以及',
    },
   {
     firstLevel:'',
     secondLevel:'惩罚记录',
     weight:'',
     remark:'丙级病例,有效投诉等',
    },
]
export  default tableData
