 const tableData = [
   //培训手册完成情况
   {
     firstLevel:'培训手册完成情况',
     secondLevel:'病种完成情况',
     weight:'',
     remark:'完成率80%',
    },
   {
     firstLevel:'',
     secondLevel:'技能操作完成',
     weight:'',
     remark:'完成率80%',
    },
   //培训工作量
   {
     firstLevel:'培训工作量',
     secondLevel:'教学查房',
     weight:'',
     remark:'每个月1次，以上加分',
    },
   {
     firstLevel:'',
     secondLevel:'小讲座',
     weight:'',
     remark:'每个月2次，以上加分',
    },
   {
     firstLevel:'',
     secondLevel:'病例讨论',
     weight:'',
     remark:'每个月2次，以上加分',
    },
   {
     firstLevel:'',
     secondLevel:'技能培训',
     weight:'',
     remark:'每个月4次，以上加分',
    },
   //培训质量
   {
     firstLevel:'培训质量',
     secondLevel:'出科考试',
     weight:'',
     remark:'出科分值，优秀，良，给分值',
    },
   {
     firstLevel:'',
     secondLevel:'定期评价',
     weight:'',
     remark:'出科分值，优秀，良，给分值',
    },
   {
     firstLevel:'',
     secondLevel:'结业考核',
     weight:'',
     remark:'通过则给分',
    },
   //日常管理
   {
     firstLevel:'日常管理',
     secondLevel:'考勤情况',
     weight:'',
     remark:'全勤加分，旷工>扣分()',
    },
   {
     firstLevel:'',
     secondLevel:'入科报道及时程度',
     weight:'',
     remark:'未及时入科报道扣分()',
    },
   {
     firstLevel:'',
     secondLevel:'手册书写完成',
     weight:'',
     remark:'按时提交(),出科一周()二周()',
    },
   {
     firstLevel:'',
     secondLevel:'教学评价完成度',
     weight:'',
     remark:'完成率80%',
    },
   {
     firstLevel:'',
     secondLevel:'奖励记录',
     weight:'',
     remark:'表扬信,优秀住院医师,以及',
    },
   {
     firstLevel:'',
     secondLevel:'惩罚记录',
     weight:'',
     remark:'丙级病例,有效投诉等',
    },
   //能力提升
   {
     firstLevel:'能力提升',
     secondLevel:'各类竞赛',
     weight:'',
     remark:'参与,获奖累加分值',
    },
]
export  default tableData
